---
title: "[USA] President Election (v3.1, temp (1976~2020) / v1 & v2, tidy)"
author: "sw1kwon"
date: "10/08/2025"
draft: false
categories: [usa-president, usa-temp-v3.1, usa-tidy-v1, usa-tidy-v2]
---

# temp3.1

In [1]:
import pandas as pd
import numpy as np

df_temp3 = pd.read_csv('https://raw.githubusercontent.com/sw1kwon/usa-elections/refs/heads/main/temp/v3_p/temp3_president.csv')

In [2]:
df_temp3.head()

,year,state,state_po,totalvotes,votes_republican,votes_democrat,votes_libertarian,votes_other,votes_writein
0,1976,ALABAMA,AL,1182850,504070,659170,1481,17821,308
1,1976,ALASKA,AK,123574,71555,44058,6785,0,1176
2,1976,ARIZONA,AZ,742719,418642,295602,7647,20806,22
3,1976,ARKANSAS,AR,767535,267903,498604,0,1028,0
4,1976,CALIFORNIA,CA,7803770,3882244,3742284,0,179242,0

In [3]:
df_temp3.assign(votes_other=lambda x: x['votes_other'] + x['votes_writein']).drop(columns=['votes_writein'])

,year,state,state_po,totalvotes,votes_republican,votes_democrat,votes_libertarian,votes_other
0,1976,ALABAMA,AL,1182850,504070,659170,1481,18129
1,1976,ALASKA,AK,123574,71555,44058,6785,1176
2,1976,ARIZONA,AZ,742719,418642,295602,7647,20828
3,1976,ARKANSAS,AR,767535,267903,498604,0,1028
4,1976,CALIFORNIA,CA,7803770,3882244,3742284,0,179242
...,...,...,...,...,...,...,...,...
607,2020,VIRGINIA,VA,4460524,1962430,2413568,64761,19765
608,2020,WASHINGTON,WA,4087631,1584651,2369612,80500,52868
609,2020,WEST VIRGINIA,WV,794652,545382,235984,10687,2599
610,2020,WISCONSIN,WI,3298041,1610184,1630866,0,56991
611,2020,WYOMING,WY,276765,193559,73491,5768,3947

In [4]:
df_temp3_1 = df_temp3.assign(votes_other=lambda x: x['votes_other'] + x['votes_writein']).drop(columns=['votes_writein'])

In [5]:
df_temp3_1.to_csv('temp3_1_president.csv', encoding='utf-8-sig', index=False)

# tidy1

In [6]:
df_temp1_1 = pd.read_csv('https://raw.githubusercontent.com/sw1kwon/usa-elections/refs/heads/main/temp/v1_1_p/temp1_1_president_2024.csv')

In [7]:
df_temp1_1.head()

,year,state,state_po,totalvotes,votes_republican,votes_democrat,votes_libertarian,votes_other
0,2024,ALABAMA,AL,2264972,1462616,772412,4930,25014
1,2024,ALASKA,AK,338177,184458,140026,3040,10653
2,2024,ARIZONA,AZ,3400986,1770242,1582860,17898,29986
3,2024,ARKANSAS,AR,1182676,759241,396905,5715,20815
4,2024,CALIFORNIA,CA,15862678,6081697,9276179,66662,438140

In [8]:
df_tidy1 = pd.concat([
    df_temp3_1, df_temp1_1
], ignore_index=True)

df_tidy1

,year,state,state_po,totalvotes,votes_republican,votes_democrat,votes_libertarian,votes_other
0,1976,ALABAMA,AL,1182850,504070,659170,1481,18129
1,1976,ALASKA,AK,123574,71555,44058,6785,1176
2,1976,ARIZONA,AZ,742719,418642,295602,7647,20828
3,1976,ARKANSAS,AR,767535,267903,498604,0,1028
4,1976,CALIFORNIA,CA,7803770,3882244,3742284,0,179242
...,...,...,...,...,...,...,...,...
658,2024,VIRGINIA,VA,4482576,2075085,2335395,19814,52282
659,2024,WASHINGTON,WA,3924243,1530923,2245849,16428,131043
660,2024,WEST VIRGINIA,WV,762390,533556,214309,3047,11478
661,2024,WISCONSIN,WI,3422918,1697626,1668229,10511,46552
662,2024,WYOMING,WY,269048,192633,69527,4193,2695

In [9]:
df_tidy1.to_csv('tidy1_president.csv', encoding='utf-8-sig', index=False)

# tidy2

In [10]:
df_temp4 = pd.read_csv('https://raw.githubusercontent.com/sw1kwon/usa-elections/refs/heads/main/temp/v4_p/temp4_president.csv')
df_temp2_2024 = pd.read_csv('https://raw.githubusercontent.com/sw1kwon/usa-elections/refs/heads/main/temp/v2_p/temp2_president_2024.csv')

In [11]:
df_temp4

,year,state,state_po,first_place_party,first_place_vote_share,second_place_party,second_place_vote_share
0,1976,ALABAMA,AL,DEMOCRAT,0.5573,REPUBLICAN,0.4261
1,1976,ALASKA,AK,REPUBLICAN,0.5790,DEMOCRAT,0.3565
2,1976,ARIZONA,AZ,REPUBLICAN,0.5637,DEMOCRAT,0.3980
3,1976,ARKANSAS,AR,DEMOCRAT,0.6496,REPUBLICAN,0.3490
4,1976,CALIFORNIA,CA,REPUBLICAN,0.4975,DEMOCRAT,0.4795
...,...,...,...,...,...,...,...
607,2020,VIRGINIA,VA,DEMOCRAT,0.5411,REPUBLICAN,0.4400
608,2020,WASHINGTON,WA,DEMOCRAT,0.5797,REPUBLICAN,0.3877
609,2020,WEST VIRGINIA,WV,REPUBLICAN,0.6863,DEMOCRAT,0.2970
610,2020,WISCONSIN,WI,DEMOCRAT,0.4945,REPUBLICAN,0.4882
611,2020,WYOMING,WY,REPUBLICAN,0.6994,DEMOCRAT,0.2655

In [12]:
df_temp2_2024.head()

,year,state,state_po,first_place_party,first_place_vote_share,second_place_party,second_place_vote_share
0,2024,ALABAMA,AL,REPUBLICAN,0.6458,DEMOCRAT,0.3410
1,2024,ALASKA,AK,REPUBLICAN,0.5454,DEMOCRAT,0.4141
2,2024,ARIZONA,AZ,REPUBLICAN,0.5205,DEMOCRAT,0.4654
3,2024,ARKANSAS,AR,REPUBLICAN,0.6420,DEMOCRAT,0.3356
4,2024,CALIFORNIA,CA,DEMOCRAT,0.5848,REPUBLICAN,0.3834

In [13]:
df_tidy2 = pd.concat([
    df_temp4, df_temp2_2024
], ignore_index=True)

df_tidy2

,year,state,state_po,first_place_party,first_place_vote_share,second_place_party,second_place_vote_share
0,1976,ALABAMA,AL,DEMOCRAT,0.5573,REPUBLICAN,0.4261
1,1976,ALASKA,AK,REPUBLICAN,0.5790,DEMOCRAT,0.3565
2,1976,ARIZONA,AZ,REPUBLICAN,0.5637,DEMOCRAT,0.3980
3,1976,ARKANSAS,AR,DEMOCRAT,0.6496,REPUBLICAN,0.3490
4,1976,CALIFORNIA,CA,REPUBLICAN,0.4975,DEMOCRAT,0.4795
...,...,...,...,...,...,...,...
658,2024,VIRGINIA,VA,DEMOCRAT,0.5210,REPUBLICAN,0.4629
659,2024,WASHINGTON,WA,DEMOCRAT,0.5723,REPUBLICAN,0.3901
660,2024,WEST VIRGINIA,WV,REPUBLICAN,0.6998,DEMOCRAT,0.2811
661,2024,WISCONSIN,WI,REPUBLICAN,0.4960,DEMOCRAT,0.4874
662,2024,WYOMING,WY,REPUBLICAN,0.7160,DEMOCRAT,0.2584

In [14]:
df_tidy2.to_csv('tidy2_president.csv', encoding='utf-8-sig', index=False)

# Batch CSV Files to ZIP

In [15]:
import zipfile
import glob

# Find all CSV files in current directory
csv_files = glob.glob('*.csv')

# Create ZIP file
with zipfile.ZipFile('all_csv_files.zip', 'w') as zipf:
   for file in csv_files:
       zipf.write(file)
       print(f"Added: {file}")  # Show progress

print(f"Total {len(csv_files)} files compressed.")

Added: tidy1_president.csv
Added: temp3_1_president.csv
Added: tidy2_president.csv
Total 3 files compressed.